"""
API routes for repo export/import (transfer).

Allows exporting an indexed repo as a .tar.gz archive and importing it
on another RoboMonkey instance, avoiding costly re-indexing and re-embedding.
"""
from __future__ import annotations

import io
import json
import logging
import tarfile
import tempfile
import uuid
from datetime import datetime, date
from pathlib import Path
from typing import Any

import asyncpg
from fastapi import APIRouter, HTTPException, UploadFile, File
from fastapi.responses import StreamingResponse

from yonk_code_robomonkey.config import Settings, get_schema_name
from yonk_code_robomonkey.db.schema_manager import (
    create_schema,
    init_schema_tables,
    list_repo_schemas,
    resolve_repo_to_schema,
)

logger = logging.getLogger(__name__)

router = APIRouter()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MANIFEST_VERSION = 1

# Tables in FK-safe dependency order (parents before children).
EXPORT_TABLE_ORDER = [
    "repo",
    "repo_index_state",
    "repo_report",
    "feature_index",
    "feature_index_embedding",
    "file",
    "symbol",
    "edge",
    "chunk",
    "chunk_embedding",
    "document",
    "document_embedding",
    "file_summary",
    "module_summary",
    "symbol_summary",
    "file_summary_embedding",
    "symbol_summary_embedding",
    "module_summary_embedding",
    "tag",
    "entity_tag",
    "tag_rule",
    "migration_assessment",
    "migration_finding",
    "migration_object_snapshot",
    "doc_validity_score",
    "doc_validity_issue",
    "behavioral_claim",
    "claim_verification",
    "doc_drift_issue",
    "sql_table_metadata",
    "sql_routine_metadata",
    "sql_column_usage",
]

# Tables that contain vector embedding columns.
EMBEDDING_TABLES = {
    "chunk_embedding",
    "document_embedding",
    "feature_index_embedding",
    "file_summary_embedding",
    "symbol_summary_embedding",
    "module_summary_embedding",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _serialize_value(val: Any) -> Any:
    """Convert a single Python/asyncpg value to a JSON-safe representation."""
    if val is None:
        return None
    if isinstance(val, uuid.UUID):
        return str(val)
    if isinstance(val, datetime):
        return val.isoformat()
    if isinstance(val, date):
        return val.isoformat()
    if isinstance(val, (list, tuple)):
        return [_serialize_value(v) for v in val]
    if isinstance(val, dict):
        return {k: _serialize_value(v) for k, v in val.items()}
    if isinstance(val, (int, float, str, bool)):
        return val
    # asyncpg returns pgvector values as strings like "[0.1,0.2,...]"
    # or as a list of floats. Handle both.
    return str(val)


def _serialize_record(record: asyncpg.Record) -> dict[str, Any]:
    """Convert an asyncpg Record to a JSON-safe dict."""
    return {key: _serialize_value(record[key]) for key in record.keys()}


async def _get_table_columns(
    conn: asyncpg.Connection, schema_name: str, table_name: str
) -> list[dict[str, str]]:
    """Get column names and types for a table."""
    rows = await conn.fetch(
        """
        SELECT column_name, data_type, udt_name
        FROM information_schema.columns
        WHERE table_schema = $1 AND table_name = $2
        ORDER BY ordinal_position
        """,
        schema_name,
        table_name,
    )
    return [
        {"name": r["column_name"], "type": r["data_type"], "udt": r["udt_name"]}
        for r in rows
    ]


def _parse_vector_string(s: str) -> list[float]:
    """Parse a pgvector string like '[0.1,0.2,0.3]' into a float list."""
    s = s.strip()
    if s.startswith("[") and s.endswith("]"):
        s = s[1:-1]
    return [float(x) for x in s.split(",") if x.strip()]


def _coerce_value(val: Any, udt: str) -> Any:
    """Coerce a JSON-deserialized value back to a Python type suitable for asyncpg."""
    if val is None:
        return None

    if udt == "uuid":
        return uuid.UUID(val) if isinstance(val, str) else val

    if udt == "timestamptz" or udt == "timestamp":
        if isinstance(val, str):
            # Handle ISO format strings
            return datetime.fromisoformat(val.replace("Z", "+00:00"))
        return val

    if udt in ("jsonb", "json"):
        # asyncpg expects a JSON string for jsonb columns
        if isinstance(val, (dict, list)):
            return json.dumps(val)
        return val

    if udt == "tsvector":
        # tsvector is auto-generated by triggers — skip it
        return None

    if udt.startswith("vector"):
        # pgvector: asyncpg expects a string like '[0.1,0.2,...]'
        if isinstance(val, list):
            return "[" + ",".join(str(f) for f in val) + "]"
        if isinstance(val, str):
            return val
        return str(val)

    if udt in ("int4", "int8", "int2"):
        return int(val) if val is not None else None

    if udt in ("float4", "float8", "numeric"):
        return float(val) if val is not None else None

    if udt == "bool":
        if isinstance(val, str):
            return val.lower() in ("true", "1", "t")
        return bool(val)

    return val


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/repos")
async def list_export_repos() -> list[dict[str, Any]]:
    """List repos available for export."""
    s = Settings()
    conn = await asyncpg.connect(dsn=s.database_url)
    try:
        repos = await list_repo_schemas(conn)
        return [
            {
                "name": r["repo_name"],
                "schema": r["schema_name"],
                "file_count": r["file_count"],
                "symbol_count": r["symbol_count"],
                "chunk_count": r["chunk_count"],
            }
            for r in repos
        ]
    finally:
        await conn.close()


@router.get("/export/{repo_name}")
async def export_repo(repo_name: str):
    """Export a repo as a streaming .tar.gz archive."""
    s = Settings()
    conn = await asyncpg.connect(dsn=s.database_url)

    try:
        repo_id, schema_name = await resolve_repo_to_schema(conn, repo_name)
    except ValueError:
        await conn.close()
        raise HTTPException(status_code=404, detail=f"Repository '{repo_name}' not found")

    async def _generate():
        """Yield tar.gz bytes as they are produced."""
        buf = io.BytesIO()
        try:
            with tarfile.open(fileobj=buf, mode="w:gz") as tar:
                table_counts: dict[str, int] = {}

                # --- Export each table ---
                for table_name in EXPORT_TABLE_ORDER:
                    # Check table exists in schema
                    exists = await conn.fetchval(
                        """
                        SELECT EXISTS (
                            SELECT 1 FROM information_schema.tables
                            WHERE table_schema = $1 AND table_name = $2
                        )
                        """,
                        schema_name,
                        table_name,
                    )
                    if not exists:
                        table_counts[table_name] = 0
                        continue

                    rows = await conn.fetch(
                        f'SELECT * FROM "{schema_name}"."{table_name}"'
                    )
                    serialized = [_serialize_record(r) for r in rows]
                    table_counts[table_name] = len(serialized)

                    data = json.dumps(serialized, ensure_ascii=False).encode("utf-8")
                    info = tarfile.TarInfo(name=f"{table_name}.json")
                    info.size = len(data)
                    tar.addfile(info, io.BytesIO(data))

                # --- Detect embedding dimension from a sample ---
                embedding_dim = s.embeddings_dimension
                try:
                    sample = await conn.fetchval(
                        f'SELECT embedding FROM "{schema_name}".chunk_embedding LIMIT 1'
                    )
                    if sample is not None:
                        if isinstance(sample, str):
                            embedding_dim = len(_parse_vector_string(sample))
                        elif isinstance(sample, (list, tuple)):
                            embedding_dim = len(sample)
                except Exception:
                    pass

                # --- Build & write manifest ---
                manifest = {
                    "version": MANIFEST_VERSION,
                    "robomonkey_version": "0.1.0",
                    "repo_name": repo_name,
                    "schema_name": schema_name,
                    "embedding_dimension": embedding_dim,
                    "exported_at": datetime.utcnow().isoformat(),
                    "tables": table_counts,
                }
                manifest_bytes = json.dumps(manifest, indent=2).encode("utf-8")
                minfo = tarfile.TarInfo(name="manifest.json")
                minfo.size = len(manifest_bytes)
                tar.addfile(minfo, io.BytesIO(manifest_bytes))

            # tarfile is now closed — buf contains the complete archive
            buf.seek(0)
            while True:
                chunk = buf.read(64 * 1024)
                if not chunk:
                    break
                yield chunk
        finally:
            await conn.close()

    filename = f"robomonkey_export_{repo_name}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.tar.gz"
    return StreamingResponse(
        _generate(),
        media_type="application/gzip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/import")
async def import_repo(file: UploadFile = File(...)) -> dict[str, Any]:
    """Import a repo from an uploaded .tar.gz archive."""
    if not file.filename or not file.filename.endswith((".tar.gz", ".tgz")):
        raise HTTPException(status_code=400, detail="File must be a .tar.gz archive")

    s = Settings()
    conn = await asyncpg.connect(dsn=s.database_url)

    warnings: list[str] = []
    tables_imported: dict[str, int] = {}

    try:
        # Read upload into memory
        content = await file.read()
        buf = io.BytesIO(content)

        with tarfile.open(fileobj=buf, mode="r:gz") as tar:
            # --- Read & validate manifest ---
            try:
                manifest_member = tar.getmember("manifest.json")
            except KeyError:
                raise HTTPException(
                    status_code=400,
                    detail="Archive missing manifest.json — not a valid RoboMonkey export",
                )

            manifest_f = tar.extractfile(manifest_member)
            if manifest_f is None:
                raise HTTPException(status_code=400, detail="Cannot read manifest.json")

            manifest: dict = json.loads(manifest_f.read().decode("utf-8"))

            if manifest.get("version", 0) > MANIFEST_VERSION:
                raise HTTPException(
                    status_code=400,
                    detail=f"Archive version {manifest['version']} is newer than supported ({MANIFEST_VERSION})",
                )

            repo_name = manifest["repo_name"]
            export_schema = manifest.get("schema_name")
            export_dim = manifest.get("embedding_dimension", 1536)
            local_dim = s.embeddings_dimension
            skip_embeddings = export_dim != local_dim

            if skip_embeddings:
                warnings.append(
                    f"Embedding dimension mismatch: archive has {export_dim}, "
                    f"local instance uses {local_dim}. Embedding tables will be "
                    f"skipped — run re-embed after import."
                )

            # --- Derive schema name, warn if it differs from export ---
            schema_name = get_schema_name(repo_name)
            if export_schema and export_schema != schema_name:
                warnings.append(
                    f"Archive schema '{export_schema}' differs from local "
                    f"schema '{schema_name}'. Importing into '{schema_name}'."
                )

            # --- Check repo doesn't already exist ---
            schema_exists = await conn.fetchval(
                """
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.schemata
                    WHERE schema_name = $1
                )
                """,
                schema_name,
            )
            if schema_exists:
                raise HTTPException(
                    status_code=409,
                    detail=f"Repository '{repo_name}' already exists (schema '{schema_name}'). "
                    f"Delete it first before importing.",
                )

            # --- Create schema & tables ---
            async with conn.transaction():
                await create_schema(conn, schema_name)
                await init_schema_tables(conn, schema_name)

                # --- Import tables in order ---
                for table_name in EXPORT_TABLE_ORDER:
                    if skip_embeddings and table_name in EMBEDDING_TABLES:
                        warnings.append(f"Skipped embedding table: {table_name}")
                        continue

                    json_name = f"{table_name}.json"
                    try:
                        member = tar.getmember(json_name)
                    except KeyError:
                        continue

                    f = tar.extractfile(member)
                    if f is None:
                        continue

                    rows: list[dict] = json.loads(f.read().decode("utf-8"))
                    if not rows:
                        tables_imported[table_name] = 0
                        continue

                    # Get column metadata for type coercion
                    columns = await _get_table_columns(conn, schema_name, table_name)
                    col_names = [c["name"] for c in columns]
                    col_udts = {c["name"]: c["udt"] for c in columns}

                    # Filter out tsvector columns (auto-generated by triggers)
                    tsvector_cols = {
                        c["name"] for c in columns if c["udt"] == "tsvector"
                    }
                    insert_cols = [c for c in col_names if c not in tsvector_cols]

                    # Build tuples for insert
                    records = []
                    for row in rows:
                        vals = []
                        for col in insert_cols:
                            raw = row.get(col)
                            vals.append(_coerce_value(raw, col_udts[col]))
                        records.append(tuple(vals))

                    # Use copy_records_to_table for fast bulk insert
                    await conn.execute(
                        f'SET search_path TO "{schema_name}", public'
                    )
                    try:
                        await conn.copy_records_to_table(
                            table_name,
                            records=records,
                            columns=insert_cols,
                            schema_name=schema_name,
                        )
                    except Exception as e:
                        # Fall back to batched inserts if COPY fails
                        logger.warning(
                            "COPY failed for %s (%s), falling back to executemany",
                            table_name,
                            e,
                        )
                        placeholders = ", ".join(
                            f"${i + 1}" for i in range(len(insert_cols))
                        )
                        col_list = ", ".join(
                            f'"{c}"' for c in insert_cols
                        )
                        insert_sql = (
                            f'INSERT INTO "{schema_name}"."{table_name}" '
                            f"({col_list}) VALUES ({placeholders})"
                        )
                        await conn.executemany(insert_sql, records)
                    finally:
                        await conn.execute("SET search_path TO public")

                    tables_imported[table_name] = len(records)

                # --- Register in control schema ---
                # Get root_path from the imported repo table
                root_path = await conn.fetchval(
                    f'SELECT root_path FROM "{schema_name}".repo LIMIT 1'
                )
                root_path = root_path or "/imported"

                # Check if control registry exists
                control_exists = await conn.fetchval(
                    """
                    SELECT EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'robomonkey_control'
                        AND table_name = 'repo_registry'
                    )
                    """
                )
                if control_exists:
                    await conn.execute(
                        """
                        INSERT INTO robomonkey_control.repo_registry
                            (name, schema_name, root_path, enabled,
                             auto_index, auto_embed, auto_watch, auto_summaries)
                        VALUES ($1, $2, $3, true, false, false, false, false)
                        ON CONFLICT (name) DO NOTHING
                        """,
                        repo_name,
                        schema_name,
                        root_path,
                    )
                else:
                    warnings.append(
                        "robomonkey_control.repo_registry not found — "
                        "repo was imported but not registered with the daemon."
                    )

        total_rows = sum(tables_imported.values())
        return {
            "status": "success",
            "repo_name": repo_name,
            "schema_name": schema_name,
            "tables_imported": tables_imported,
            "rows_imported": total_rows,
            "embedding_dimension_match": not skip_embeddings,
            "warnings": warnings,
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Import failed")
        raise HTTPException(status_code=500, detail=f"Import failed: {e}")
    finally:
        await conn.close()
