#!/bin/bash
#
# RoboMonkey Source Directory Manager
#
# Makes it easy to add/remove source code directories for indexing
# without needing to understand Docker volume mounts.
#
# Usage:
#   ./scripts/manage-sources.sh add /path/to/your/code [name]
#   ./scripts/manage-sources.sh list
#   ./scripts/manage-sources.sh remove <name>
#   ./scripts/manage-sources.sh apply   # Restart daemon with current config
#
# Examples:
#   ./scripts/manage-sources.sh add ~/projects/myapp myapp
#   ./scripts/manage-sources.sh add /home/user/work/api
#   ./scripts/manage-sources.sh list
#   ./scripts/manage-sources.sh remove myapp

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SOURCES_FILE="$PROJECT_DIR/config/sources.conf"
OVERRIDE_FILE="$PROJECT_DIR/docker-compose.override.yml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Ensure config directory exists
mkdir -p "$PROJECT_DIR/config"

# Create sources.conf if it doesn't exist
if [[ ! -f "$SOURCES_FILE" ]]; then
    cat > "$SOURCES_FILE" << 'EOF'
# RoboMonkey Source Directories
#
# Format: /host/path:name
# The name is used as the mount point inside the container (/source/name)
# and as the default repository name when indexing.
#
# Examples:
#   /home/user/projects/myapp:myapp
#   /home/user/work/api-server:api
#
# Lines starting with # are comments
EOF
fi

generate_override() {
    # Generate docker-compose.override.yml from sources.conf
    local volumes=""
    local path_map=""

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// }" ]] && continue

        # Parse host_path:name
        local host_path="${line%%:*}"
        local name="${line##*:}"

        # Expand ~ to home directory
        host_path="${host_path/#\~/$HOME}"

        # Validate path exists
        if [[ ! -d "$host_path" ]]; then
            echo -e "${YELLOW}Warning: Path does not exist: $host_path${NC}" >&2
            continue
        fi

        # Get absolute path
        host_path="$(cd "$host_path" && pwd)"

        # Add to volumes list
        volumes="${volumes}      - ${host_path}:/source/${name}:ro\n"

        # Add to path map (host:container format for the indexer)
        if [[ -n "$path_map" ]]; then
            path_map="${path_map},"
        fi
        path_map="${path_map}${host_path}:/source/${name}"

    done < "$SOURCES_FILE"

    if [[ -z "$volumes" ]]; then
        # No sources configured - remove override file if it exists
        rm -f "$OVERRIDE_FILE"
        return 0
    fi

    # Generate the override file
    cat > "$OVERRIDE_FILE" << EOF
# Auto-generated by manage-sources.sh - DO NOT EDIT MANUALLY
# Run ./scripts/manage-sources.sh to modify source directories

services:
  daemon:
    volumes:
      - ./config:/app/config:ro
$(echo -e "$volumes" | sed '/^$/d')
    environment:
      SOURCE_PATH_MAP: "${path_map}"
EOF

    echo -e "${GREEN}Generated $OVERRIDE_FILE${NC}"
}

cmd_add() {
    local host_path="$1"
    local name="$2"

    if [[ -z "$host_path" ]]; then
        echo -e "${RED}Error: Please provide a path${NC}"
        echo "Usage: $0 add /path/to/code [name]"
        exit 1
    fi

    # Expand ~ to home directory
    host_path="${host_path/#\~/$HOME}"

    # Validate path exists
    if [[ ! -d "$host_path" ]]; then
        echo -e "${RED}Error: Directory does not exist: $host_path${NC}"
        exit 1
    fi

    # Get absolute path
    host_path="$(cd "$host_path" && pwd)"

    # Auto-generate name from directory if not provided
    if [[ -z "$name" ]]; then
        name="$(basename "$host_path")"
        # Sanitize name (lowercase, replace spaces/special chars with dashes)
        name="$(echo "$name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')"
    fi

    # Check if name already exists
    if grep -q ":${name}$" "$SOURCES_FILE" 2>/dev/null; then
        echo -e "${YELLOW}Warning: Name '$name' already exists. Updating path.${NC}"
        # Remove old entry
        sed -i.bak "/:${name}$/d" "$SOURCES_FILE"
        rm -f "${SOURCES_FILE}.bak"
    fi

    # Add to sources.conf
    echo "${host_path}:${name}" >> "$SOURCES_FILE"
    echo -e "${GREEN}Added source: ${host_path} as '${name}'${NC}"

    # Regenerate override file
    generate_override

    echo ""
    echo -e "${BLUE}To apply changes, run:${NC}"
    echo "  docker compose down daemon && docker compose up -d daemon"
    echo ""
    echo -e "${BLUE}Then index the repository:${NC}"
    echo "  docker exec robomonkey-daemon robomonkey index --repo /source/${name} --name ${name}"
}

cmd_list() {
    echo -e "${BLUE}Configured source directories:${NC}"
    echo ""

    local count=0
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// }" ]] && continue

        local host_path="${line%%:*}"
        local name="${line##*:}"

        # Expand ~ for display
        host_path="${host_path/#\~/$HOME}"

        # Check if path exists
        if [[ -d "$host_path" ]]; then
            echo -e "  ${GREEN}[OK]${NC} ${name}"
            echo "       Host: $host_path"
            echo "       Container: /source/${name}"
        else
            echo -e "  ${RED}[MISSING]${NC} ${name}"
            echo "       Host: $host_path (does not exist)"
        fi
        echo ""
        ((count++))
    done < "$SOURCES_FILE"

    if [[ $count -eq 0 ]]; then
        echo "  No sources configured yet."
        echo ""
        echo "  Add a source with:"
        echo "    $0 add /path/to/your/code"
    fi
}

cmd_remove() {
    local name="$1"

    if [[ -z "$name" ]]; then
        echo -e "${RED}Error: Please provide a name to remove${NC}"
        echo "Usage: $0 remove <name>"
        echo ""
        echo "Current sources:"
        cmd_list
        exit 1
    fi

    if ! grep -q ":${name}$" "$SOURCES_FILE" 2>/dev/null; then
        echo -e "${RED}Error: Source '$name' not found${NC}"
        exit 1
    fi

    # Remove entry
    sed -i.bak "/:${name}$/d" "$SOURCES_FILE"
    rm -f "${SOURCES_FILE}.bak"

    echo -e "${GREEN}Removed source: ${name}${NC}"

    # Regenerate override file
    generate_override

    echo ""
    echo -e "${BLUE}To apply changes, run:${NC}"
    echo "  docker compose down daemon && docker compose up -d daemon"
}

cmd_apply() {
    echo -e "${BLUE}Regenerating configuration...${NC}"
    generate_override

    echo ""
    echo -e "${BLUE}Restarting daemon...${NC}"
    cd "$PROJECT_DIR"
    docker compose down daemon 2>/dev/null || true
    docker compose up -d daemon

    echo ""
    echo -e "${GREEN}Done! Daemon restarted with updated source mounts.${NC}"
    echo ""
    echo "Verify mounts with:"
    echo "  docker exec robomonkey-daemon ls -la /source/"
}

cmd_help() {
    cat << EOF
RoboMonkey Source Directory Manager

Usage: $0 <command> [arguments]

Commands:
  add <path> [name]   Add a source directory to index
                      Path: absolute or relative path to your code
                      Name: optional identifier (defaults to directory name)

  list                Show all configured source directories

  remove <name>       Remove a source directory by name

  apply               Regenerate config and restart daemon

Examples:
  $0 add ~/projects/myapp
  $0 add /home/user/work/api-server api
  $0 list
  $0 remove myapp
  $0 apply

After adding a source, index it with:
  docker exec robomonkey-daemon robomonkey index --repo /source/<name> --name <name>

EOF
}

# Main command router
case "${1:-help}" in
    add)
        cmd_add "$2" "$3"
        ;;
    list|ls)
        cmd_list
        ;;
    remove|rm)
        cmd_remove "$2"
        ;;
    apply|restart)
        cmd_apply
        ;;
    help|--help|-h)
        cmd_help
        ;;
    *)
        echo -e "${RED}Unknown command: $1${NC}"
        echo ""
        cmd_help
        exit 1
        ;;
esac
